name: bubble_pumping
description: "Sky Bubble Burst - Kids Game"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_datepicker: ^28.1.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash_screen.png
    - assets/images/logo.png
    - assets/voice/bubble.mp3
    - assets/voice/bubble_pop.mp3
    - assets/backgrounds/
